# Generated by Django 3.2.5 on 2021-07-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(
                choices=[("eyoba", "Eyob"), ("miko", "Miki")], max_length=5
            ),
        ),
    ]
